name: Rust

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Versions
      run: rustc --version && cargo --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
